apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginxapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 15Mi
          cpu: 50m
